# Generated by Django 2.1 on 2019-07-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='weight'),
        ),
    ]
