# Generated by Django 2.1 on 2019-07-06 21:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='create_time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update_time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete_tag')),
                ('order_id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='order_id')),
                ('user', models.CharField(max_length=100, verbose_name='user')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='email')),
                ('phone_number', models.CharField(max_length=30, verbose_name='phone')),
                ('addr', models.CharField(max_length=255, verbose_name='shipping_address')),
                ('zip_code', models.CharField(max_length=100, verbose_name='zip code')),
                ('city', models.CharField(default='', max_length=100, verbose_name='city')),
                ('state', models.CharField(max_length=100, verbose_name='state')),
            ],
            options={
                'ordering': ('order_id',),
            },
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='create_time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update_time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete_tag')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='subtotal')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderInfo', verbose_name='orderid')),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='product')),
            ],
            options={
                'ordering': ('orderId',),
            },
        ),
    ]
