# Generated by Django 2.1 on 2019-07-08 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190707_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='total_count',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='total_price',
        ),
    ]
