# Generated by Django 2.1 on 2019-07-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190707_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='total_price'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='total_quantity',
            field=models.IntegerField(default=1, verbose_name='purchase_number'),
        ),
    ]
