# Generated by Django 2.1 on 2019-07-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20190710_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_method',
            field=models.SmallIntegerField(choices=[(1, 'PAYPAL'), (2, 'CREDIT CARD')], default=1, verbose_name='pay_method'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='total_quantity',
            field=models.IntegerField(default=0, verbose_name='total_quantity'),
        ),
    ]
