# Generated by Django 2.1 on 2019-07-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20190710_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='total_weight',
            field=models.IntegerField(default=0, verbose_name='total_weight'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='trade_no',
            field=models.CharField(default='', max_length=128, verbose_name='trade_number'),
        ),
    ]
